### ISSUE TITLE
如何启用推送相关功能？

### ISSUE THREAD

**Issue by Higanoneko** [Zerolouis/skyland_auto_sign_qinglong#1]
~看到脚本内有推送相关的文件，如何启用？~
 
是青龙自己添加的，我研究一下

**Comment by Zerolouis** [comment]
青龙自己会自己生成一个通知脚本，在脚本管理-这个项目的文件夹下面，填上对应的api然后在函数里调用就行了，晚上我来添加一下消息推送
![image](https://github.com/Zerolouis/skyland_auto_sign_qinglong/assets/56797379/9da6a9e0-85ae-4493-b2e3-33c3340b8e94)
![image](https://github.com/Zerolouis/skyland_auto_sign_qinglong/assets/56797379/eedd5d56-bcc8-449c-8f65-a80781f7939f)

**Comment by Zerolouis** [comment]
已经推送了，重新订阅下
