### ISSUE TITLE
是否考虑把推送API写入环境变量？

### ISSUE THREAD

**Issue by ghost** [Zerolouis/skyland_auto_sign_qinglong#12]
青龙面板自动拉库更新好像会导致notify.py重置（推送API丢失），当然，，手动改下定时规则也能解决就是了。

**Comment by Zerolouis** [comment]
推送脚本会直接使用系统变量的，你只要在青龙面板的配置文件中配好就可以了
我之前就填了，就一直没发现推送会重置的问题
![image](https://github.com/Zerolouis/skyland_auto_sign_qinglong/assets/56797379/0a4ee659-695f-46c8-9232-b41c59183d6e)
