### ISSUE TITLE
2024-09-10 无法签到

### ISSUE THREAD

**Issue by Higanoneko** [Zerolouis/skyland_auto_sign_qinglong#13]
疑似丫丁瞎jb改又把东西改掉了
```
ERROR:root:签到完全失败了！: 
Traceback (most recent call last):
  File "/ql/data/scripts/Zerolouis_skyland_auto_sign_qinglong_master/auto_sign.py", line 268, in start
    cred = login_by_token(token)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/ql/data/scripts/Zerolouis_skyland_auto_sign_qinglong_master/auto_sign.py", line 167, in login_by_token
    return get_cred(grant_code)
           ^^^^^^^^^^^^^^^^^^^^
  File "/ql/data/scripts/Zerolouis_skyland_auto_sign_qinglong_master/auto_sign.py", line 179, in get_cred
    }, headers=header_login).json()
                             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by Zerolouis** [comment]
看上游说是这个地址
https://zonai.skland.com/api/v1/user/auth/generate_cred_by_code
无法访问了

**Comment by PianCat** [comment]
> 看上游说是这个地址 https://zonai.skland.com/api/v1/user/auth/generate_cred_by_code 无法访问了

感觉得修改访问模式了，模拟森空岛访问？

**Comment by Higanoneko** [comment]
找到一个可用的Python版本：
`https://github.com/HaneRo/skland_arknights_checkin`

**Comment by Higanoneko** [comment]
原来是风控了，那没办法了

**Comment by CHNZYX** [comment]
很抱歉，由于您访问的URL有可能对网站造成安全威胁，您的访问被阻断
<Response [405]>

**Comment by karhow** [comment]
同样遇到这个问题

**Comment by w211691** [comment]
> 看上游说是这个地址 https://zonai.skland.com/api/v1/user/auth/generate_cred_by_code 无法访问了

这个脚本报错。。。

**Comment by w211691** [comment]
> 找到一个可用的Python版本： `https://github.com/HaneRo/skland_arknights_checkin`

这个脚本报差不多的错误，YJ估计全封禁了

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ql/data/scripts/skland_arknights_checkin.py", line 140, in <module>
    cred,token = get_cred(code)
                 ^^^^^^^^^^^^^^
  File "/ql/data/scripts/skland_arknights_checkin.py", line 134, in get_cred
    if response.json()['code'] == 0:
       ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Higanoneko** [comment]
> 很抱歉，由于您访问的URL有可能对网站造成安全威胁，您的访问被阻断 <Response [405]>

有了：
根据隔壁Nodejs的Issue区找到了另一种解决方案，不走API而是走Web
https://github.com/enpitsuLin/skland-daily-attendance/issues/50#issuecomment-2378326844
只需要did就行，did可以在登录的时候抓取，就是后面的get_cred那一块需要额外做处理

**Comment by Zerolouis** [comment]
> > 很抱歉，由于您访问的URL有可能对网站造成安全威胁，您的访问被阻断 <Response [405]>
> 
> 有了： 根据隔壁Nodejs的Issue区找到了另一种解决方案，不走API而是走Web [enpitsuLin/skland-daily-attendance#50 (comment)](https://github.com/enpitsuLin/skland-daily-attendance/issues/50#issuecomment-2378326844) 只需要did就行，did可以在登录的时候抓取，就是后面的get_cred那一块需要额外做处理

看到了，我来修改下

**Comment by xxyz30** [comment]
看源项目
https://gitee.com/FancyCabbage/skyland-auto-sign

**Comment by Higanoneko** [comment]
> > > 很抱歉，由于您访问的URL有可能对网站造成安全威胁，您的访问被阻断 <Response [405]>
> > 
> > 
> > 有了： 根据隔壁Nodejs的Issue区找到了另一种解决方案，不走API而是走Web [enpitsuLin/skland-daily-attendance#50 (comment)](https://github.com/enpitsuLin/skland-daily-attendance/issues/50#issuecomment-2378326844) 只需要did就行，did可以在登录的时候抓取，就是后面的get_cred那一块需要额外做处理
> 
> 看到了，我来修改下

源项目更新了处理方法了

**Comment by Domgur0** [comment]
我fork后，对着源代码乱改一通，现在成功运行了，但代码很乱，毕竟我没什么基础很多都看不懂，只是把对面不一样的复制过来，然后有报错才去一个个溯源。
我的项目：https://github.com/Domgur0/skyland_auto_sign_qinglong
修改后的代码文件名字是“ql.py”，并且添加了邮箱推送！希望大佬们可以再完善一下

**Comment by Higanoneko** [comment]
> 我fork后，对着源代码乱改一通，现在成功运行了，但代码很乱，毕竟我没什么基础很多都看不懂，只是把对面不一样的复制过来，然后有报错才去一个个溯源。 我的项目：https://github.com/Domgur0/skyland_auto_sign_qinglong 修改后的代码文件名字是“ql.py”，并且添加了邮箱推送！希望大佬们可以再完善一下

谢谢，这个很有用
