### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by DangoPie** [Zerolouis/skyland_auto_sign_qinglong#8]
## 开始执行... 2023-10-25 15:23:10

  File "/ql/scripts/Zerolouis_skyland_auto_sign_qinglong/auto_sign.py", line 78
    match type:
          ^
SyntaxError: invalid syntax

## 执行结束... 2023-10-25 15:23:10 耗时 0 秒

通知选用钉钉，机器人相关token和secret均已填写，python的requests依赖也已经安装

**Comment by Zerolouis** [comment]
python 版本低了，match-case语法是3.10新增的，稍后改成if else

**Comment by DangoPie** [comment]
感谢大佬

**Comment by Zerolouis** [comment]
#9
